name: Update txt URL list
on:
push:
paths:
- 'RM2.6兑换资源/**'
- '.github/workflows/update-url-list.yml'
workflow_dispatch:   # 手动按钮，随时可点
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v3
with:
ref: RM2.6%E5%85%91%E6%8D%A2%E8%B5%84%E6%BA%90   # 明确切到该分支
token: ${{ secrets.GITHUB_TOKEN }}
- name: Generate url_list.txt
    run: |
      find RM2.6兑换资源 -type f -name '*.txt' | sort > /tmp/files
      {
        echo '# 自动生成，请勿手动编辑'
        echo '# 每行一个 RAW 地址，方便批量读取'
        while IFS= read -r f; do
          echo "https://raw.githubusercontent.com/a210076/-/RM2.6%E5%85%91%E6%8D%A2%E8%B5%84%E6%BA%90/$f"
        done < /tmp/files
      } > url_list.txt

  - name: Commit & push
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git add url_list.txt
      git diff --cached --quiet || (
        git commit -m "chore: auto-update url_list.txt"
        git push
      )
